DdangDdang5/Frontend

- src/elements/button/Button.jsx
- src/index.js
- src/pages/login/Login.jsx
- src/pages/main/Main.jsx
- src/pages/signUp/SignUp.jsx
- src/redux/modules/MemberSlice.js
#5 
[Feat] 로그인, 회원가입, 카카오 로그인 View 완성
> [Feat] 로그인, 회원가입 View 구현

- src/App.js
- src/components/auction/Auction.jsx
- src/components/footer/Footer.styled.js
- src/components/modal/Modal.jsx
- src/pages/auctionDetail/AuctionDetail.jsx
- src/pages/auctionList/AuctionList.jsx
- src/pages/mypage/Mypage.jsx
#7 
옥션 추가 페이지 일단 디자인 나온 부분까지 완성.
마이 프로필 페이지 뷰 구현중
> [Feat] 마이프로필 페이지 구현중!

- src/components/auction/Auction.jsx
- src/pages/auctionList/AuctionList.jsx
- src/pages/mypage/Mypage.jsx
> [bug]  서버 배포시 파일명 오류로 인해 파일명 수정

- src/components/auction/Auction.jsx
- src/components/footer/Footer.styled.js
- src/pages/auctionList/AuctionList.jsx
- src/redux/modules/AuctionListSlice.js
- src/shared/Api.jsx
> [Feat]auctionList css 레이아웃 변경

- src/App.js
- src/components/auctionCategory/AuctionCategory.jsx
- src/components/auctionCategory/AuctionCategory.styled.js
- src/components/auctionCategoryList/AuctionCategoryList.jsx
- src/components/auctionCategoryList/AuctionCategoryList.styled.js
- src/components/chatRoom/ChatRoom.styled.js
- src/pages/main/Main.jsx
- src/pages/main/Main.styled.js
feat: 메인화면 View 구현 (마감임박 경매 수정 필요)
> feat: 메인화면 View 구현 (마감임박 경매 수정 필요)

- src/App.js
- src/components/auctionCategoryList/AuctionCategoryList.jsx
- src/components/auctionCategoryList/AuctionCategoryList.styled.js
- src/components/footer/Footer.jsx
- src/components/footer/Footer.styled.js
- src/components/header/Header.jsx
- src/components/header/Header.styled.js
- src/components/swipeImage/SwipeImage.jsx
- src/components/swipeImage/SwipeImage.styled.js
- src/index.css
- src/pages/chatList/ChatList.styled.js
- src/pages/main/Main.jsx
- src/pages/main/Main.styled.js
- src/redux/config/ConfigStore.js
- src/redux/modules/AuctionDivisionSlice.js
[Feat] 메인화면 View 구현완료, 이미지 슬라이드 기능 구현 #17
> [Feat] 메인화면 View 구현완료, 이미지 슬라이드 기능 구현

- src/components/auction/Auction.jsx
- src/components/footer/Footer.styled.js
- src/components/header/Header.styled.js
- src/index.css
- src/pages/auctionDetail/AuctionDetail.jsx
- src/pages/auctionList/AuctionList.jsx
- src/pages/myPage/MyPage.jsx
- src/pages/profileEdit/ProfileEdit.jsx
페이지 뷰 디자인 나온대로 차례로 완성중
현대 프로필 메인은 안나와서 수정 먼저
리스트 디테일 뷰는 디자인 나온것 까지만 완성
#18
> [Feat] 옥션 리스트 페이지 뷰, 리스트 디테일 페이지 뷰, 프로필 수정 페이지 뷰 완성

- src/App.js
- src/components/auction/Auction.jsx
- src/components/footer/Footer.styled.js
- src/components/modal/Modal.jsx
- src/pages/auctionDetail/AuctionDetail.jsx
- src/pages/auctionList/AuctionList.jsx
- src/pages/myPage/MyPage.jsx
- src/pages/profileEdit/ProfileEdit.jsx
- src/redux/config/ConfigStore.js
- src/redux/modules/AuctionListSlice.js
- src/redux/modules/AuctionSlice.js
- src/shared/Api.jsx
auction list 완료
detail 진행중
#20
> [Feat] 서버 연결 뿌려주기 진행중

- src/components/auctionCategoryList/AuctionCategoryList.jsx
- src/components/chatRoom/ChatRoom.jsx
- src/components/chatRoom/ChatRoom.styled.js
- src/components/swipeImage/SwipeImage.jsx
- src/components/swipeImage/SwipeImage.styled.js
- src/pages/chatList/ChatList.jsx
- src/pages/chatList/ChatList.styled.js
- src/pages/main/Main.jsx
- src/pages/main/Main.styled.js
- src/redux/modules/AuctionDivisionSlice.js
- src/redux/modules/AuctionListSlice.js
[Feat] 메인화면 기능 구현 완료 #17 
[Modify] 채팅방 목록 View 수정 #3
> [Feat] 메인화면 기능 구현 완료, [Modify] 채팅방 목록 View 수정

- src/components/auction/Auction.jsx
- src/pages/auctionDetail/AuctionDetail.jsx
- src/pages/auctionList/AuctionList.jsx
- src/redux/modules/AuctionListSlice.js
- src/redux/modules/AuctionSlice.js
get 요청을 하면 이미지나 기타등을 불러올때 갑자기 서버 통신 먹통이 되는걸 수정중
> [modify] auctionDetail 서버 데이터 get 오류 수정중

- src/App.js
- src/components/modal/Modal.jsx
- src/index.js
- src/pages/auctionDetail/AuctionDetail.jsx
- src/pages/auctionList/AuctionList.jsx
- src/redux/config/ConfigStore.js
- src/redux/modules/AuctionSlice.js
- src/redux/modules/ModalSlice.js
- src/redux/modules/MypageSlice.js
> [feat] auctionList 지역 modal view 구현 완료

- src/components/auction/Auction.jsx
- src/components/modal/Modal.jsx
- src/pages/auctionList/AuctionList.jsx
> [feat] auctionList modal 웹페이지 모바일 페이지 완벽 뷰 구현

- src/App.js
- src/pages/login/Login.jsx
- src/pages/login/Login.styled.jsx
- src/pages/signUp/SignUp.jsx
- src/redux/modules/MemberSlice.js
- src/shared/Cookie.jsx
- src/shared/Kakao.jsx
> [Feat] 소셜 로그인 수정

- src/App.js
- src/components/button/PlusButton.jsx
- src/components/footer/Footer.jsx
- src/components/modal/Modal.jsx
- src/pages/auctionDetail/AuctionDetail.jsx
- src/pages/auctionList/AuctionList.jsx
- src/redux/modules/ModalSlice.js
> [Feat] 옥션 상세 페이지 하단부 구현중, 플러스 버튼 컴포넌트 생성

- src/App.js
- src/components/search/TitleSearch.jsx
- src/pages/login/Login.jsx
- src/pages/login/Login.styled.jsx
- src/pages/search/Search.jsx
- src/pages/search/SearchTitle.jsx
- src/pages/signUp/SignUp.jsx
- src/pages/signUp/SignUp.styled.jsx
- src/redux/modules/MemberSlice.js
- src/shared/Theme.jsx
> [Feat] 검색 화면 View 구현

- public/index.html
- src/components/auctionCategory/AuctionCategory.jsx
- src/components/auctionCategoryList/AuctionCategoryList.jsx
- src/components/header/Header.jsx
- src/components/swipeImage/SwipeImage.jsx
- src/components/swipeImage/SwipeImage.styled.js
- src/pages/main/Main.jsx
- src/pages/main/Main.styled.js
- src/redux/modules/AuctionDivisionSlice.js
[Modify] 메인화면 이미지 위 색 레이어 추가 #17
> [Modify] 메인화면 이미지 위 색 레이어 추가 

- src/App.js
- src/components/button/PlusButton.jsx
- src/components/modal/CategoryModal.jsx
> [Feat] 포스팅 이중모달 만드는중

- src/App.js
- src/components/auction2/Auction2.jsx
- src/components/auctionStateNav/AuctionStateNav.jsx
- src/components/button/PlusButton.jsx
- src/components/modal/PlusBtnBoxModal.jsx
- src/pages/auctionList/AuctionList.jsx
- src/pages/auctionWrite/AuctionWrite.jsx
- src/pages/myPage/MyPage.jsx
- src/pages/myPage/MyPageInterestAuction.jsx
- src/pages/myPage/MyPageMyAuction.jsx
- src/pages/myPage/MyPageParticipationAuction.jsx
#20 
관심, 참여, 뷰는 컴포넌트로 뿌려 놨는데, 이게 페이지별로 구분하여 프롭스로 내려줄 수 있는지 확인해야함. 아니면 따로 만들어서 추가
> [Feat] 옥션 추가 페이지 뷰, 마이페이지 뷰, 관심, 참여, 경매 뷰 완료 

- src/App.js
- src/components/header/Header.jsx
- src/components/header/Header.styled.js
- src/components/swipeImage/SwipeImage.styled.js
- src/index.js
- src/pages/auctionDetail/AuctionDetail.jsx
- src/pages/auctionReview/AuctionReview.jsx
- src/pages/auctionReview/AuctionReview.styled.js
- src/pages/main/Main.styled.js
- src/pages/myGrade/MyGrade.jsx
- src/pages/myGrade/MyGrade.styled.js
- src/pages/myPage/MyPage.jsx
- src/shared/Theme.jsx
> [Feat] 신뢰도 화면, 평가 화면 View 구현

- src/App.js
[Modify] App.js import Modal 삭제
> [Modify] App.js import Modal 삭제

- src/App.js
- src/components/button/PlusButton.jsx
- src/pages/auctionWrite/AuctionWrite.jsx
- src/redux/modules/AuctionListSlice.js
- src/redux/modules/AuctionSlice.js
- src/redux/modules/MemberSlice.js
- src/shared/Api.jsx
> [Feat] 옥션 포스팅 기능 서버 통신완료

- src/components/auction/AuctionRow.jsx
- src/components/header/Header.jsx
- src/components/modal/menuModal.jsx
- src/pages/auctionDetail/AuctionDetail.jsx
- src/pages/auctionWrite/AuctionWrite.jsx
- src/pages/myPage/MyPage.jsx
- src/pages/myPage/MyPageInterestAuction.jsx
- src/pages/myPage/MyPageMyAuction.jsx
- src/pages/myPage/MyPageParticipationAuction.jsx
- src/pages/profileEdit/ProfileEdit.jsx
- src/pages/search/Search.jsx
- src/redux/modules/AuctionListSlice.js
- src/redux/modules/MypageSlice.js
> [Feat] 마이페이지 수정 기능 기본 완료, 콘솔 삭제, 기타 수정들 

- src/components/header/Header.jsx
- src/pages/auctionDetail/AuctionDetail.jsx
- src/pages/auctionList/AuctionList.jsx
- src/redux/modules/AuctionListSlice.js
옥션 포스트 삭제하면 뒤로가기는 되는데 새로고침 안됨면 삭제가 반영 안되던것 async await 써서 해결 
#61
> [feat] 옥션리스트 삭제후 새로고침 안하면 랜더링 안되던것 해결

- public/index.html
- src/components/chatRoom/ChatRoom.jsx
- src/components/modal/MenuModal.jsx
- src/pages/auctionDetail/AuctionDetail.jsx
- src/pages/chat/Chat.jsx
- src/pages/chat/Chat.styled.js
- src/pages/chatList/ChatList.jsx
- src/pages/chatList/ChatList.styled.js
- src/pages/main/Main.jsx
- src/pages/main/Main.styled.js
- src/redux/modules/ChatSlice.js
[Feat]
- 채팅방 이전 기록 가져오기 #4 
- 메뉴 모달 구현 #4
> [Feat] 채팅방 이전 기록 가져오기, 메뉴 모달 구현

- src/components/auction/Slider.jsx
- src/components/modal/menuModal.jsx
- src/pages/auctionDetail/AuctionDetail.jsx
- src/pages/login/Login.jsx
- src/pages/myPage/MyPage.jsx
- src/pages/myPage/MyPageMyAuction.jsx
- src/pages/profileEdit/ProfileEdit.jsx
- src/redux/modules/MypageSlice.js
- src/shared/Api.jsx
#61 
이미지 슬라이더 지금 참고자료 보면서 만드는중!
> [Feat] 로그인 기능 추가, 이미지 슬라이더 만드는중

- src/components/auction/Slider.jsx
- src/pages/auctionDetail/AuctionDetail.jsx
- src/pages/auctionWrite/AuctionWrite.jsx
> [Feat] 이미지 슬라이드 기본 기능 완료

- src/components/auction/AuctionRow.jsx
- src/pages/auctionDetail/AuctionDetail.jsx
- src/pages/myPage/MyPage.jsx
- src/pages/myPage/MyPageInterestAuction.jsx
- src/pages/myPage/MyPageMyAuction.jsx
- src/pages/profileEdit/ProfileEdit.jsx
- src/redux/modules/MyPageSlice.js
> [feat] 마이페이지 괸심 수정

- src/components/search/SearchHistory.jsx
- src/components/search/SearchHistory.styled.jsx
- src/components/search/SearchResult.jsx
- src/components/search/SearchResult.styled.jsx
- src/pages/login/Login.jsx
- src/pages/search/Search.jsx
- src/pages/search/Search.styled.jsx
- src/pages/signUp/SignUp.jsx
- src/redux/modules/MemberSlice.js
- src/redux/modules/SearchSlice.js
> [Feat] 회원가입 페이지 코드 수정

- src/components/search/SearchHistory.jsx
- src/components/search/SearchResult.styled.jsx
- src/pages/search/Search.jsx
- src/pages/search/Search.styled.jsx
- src/pages/signUp/SignUp.jsx
- src/pages/signUp/SignUp.styled.jsx
- src/redux/modules/SearchSlice.js
> [Feat] 회원가입 오류 수정

- src/App.js
> [Modify] App.js 충돌 해결

- src/App.js
- src/components/auctionBody/AuctionColumn.jsx
- src/components/auctionCategoryList/AuctionCategoryList.jsx
- src/components/chatRoom/ChatRoom.jsx
- src/components/header/Header.jsx
- src/components/modal/CategoryModal.jsx
- src/components/swipeImage/SwipeImage.jsx
- src/components/swipeImage/SwipeImage.styled.js
- src/pages/auctionDetail/AuctionDetail.jsx
- src/pages/auctionList/AuctionList.jsx
- src/pages/auctionReview/AuctionReview.styled.js
- src/pages/chat/Chat.jsx
- src/pages/chat/Chat.styled.js
- src/pages/chatList/ChatList.jsx
- src/pages/event/Event.jsx
- src/pages/eventList/EventList.jsx
- src/pages/main/Main.jsx
- src/pages/main/Main.styled.js
- src/redux/modules/ChatSlice.js
- src/redux/modules/ModalSlice.js
- src/shared/Api.jsx
[Feat] 경매 목록 분류 모달 애니메이션, 채팅화면 이동 시 새로고침
[Modify] 채팅 로딩 시간, 내역 불러오기 수정
> [Feat] 경매 목록 분류 모달 애니메이션, 채팅화면 이동 시 새로고침, [Modify] 채팅 로딩 시간, 내역 불러오기 수정

- public/index.html
- src/components/search/SearchHistory.jsx
- src/components/search/SearchHistory.styled.jsx
- src/elements/button/Button.jsx
- src/pages/login/Login.jsx
- src/pages/search/Search.jsx
- src/pages/signUp/SignUp.jsx
- src/pages/signUp/SignUp.styled.jsx
> [Feat] 코드 일부 수정 및 hotjar 연결

- src/components/search/SearchHistory.styled.jsx
- src/pages/search/Search.styled.jsx
> [Modify] 검색 화면 기능 일부 수정

- src/components/search/SearchHistory.styled.jsx
- src/pages/search/Search.styled.jsx
Revert "[Modify] 검색 화면 기능 일부 수정"
> Revert "[Modify] 검색 화면 기능 일부 수정"

- src/components/header/Header.styled.js
- src/pages/chat/Chat.jsx
- src/shared/images/icon/Menu.svg
[Modify] 채팅 시간 수정, 헤더 메뉴 버튼 수정
> [Modify] 채팅 시간 수정, 헤더 메뉴 버튼 수정

- src/components/footer/Footer.jsx
- src/components/footer/Footer.styled.js
- src/components/modal/MenuModal.jsx
- src/components/modal/PageModal.jsx
- src/elements/button/PlusButton.jsx
- src/pages/auctionDetail/AuctionDetail.jsx
- src/pages/auctionReview/AuctionReview.jsx
- src/pages/auctionWrite/AuctionWrite.jsx
- src/pages/chat/Chat.jsx
- src/pages/event/Event.jsx
- src/pages/main/Main.jsx
- src/pages/main/Main.styled.js
- src/pages/myPage/MyPage.jsx
- src/pages/myPage/MyPageMyAuction.jsx
[Feat] window.alert, window.confirm 모달 적용
> [Feat] window.alert, window.confirm 모달 적용

- src/components/modal/PageModal.jsx
- src/pages/auctionDetail/AuctionDetail.jsx
- src/pages/chat/Chat.jsx
- src/pages/myPage/MyPage.jsx
- src/pages/search/Search.jsx
- src/redux/modules/MemberSlice.js
[Modify] 검색화면, 채팅, 마이페이지 코드 수정
> [Modify] 검색화면, 채팅, 마이페이지 코드 수정

- src/components/modal/PageModal.jsx
> [Modify] pageModal 충돌 해결

- src/components/modal/PageModal.jsx
- src/pages/auctionDetail/AuctionDetail.jsx
- src/pages/myPage/MyPage.jsx
- src/redux/modules/MemberSlice.js
[Modify] 채팅, 마이페이지, 카카오 로그인 일부 오류 수정
> [Modify] 채팅, 마이페이지, 카카오 로그인 일부 오류 수정

- src/pages/auctionDetail/AuctionDetail.jsx
- src/pages/main/Main.styled.js
- src/pages/myPage/MyPage.jsx
- src/pages/myPage/MyPageMyAuction.jsx
- src/pages/userProfile/UserProfile.jsx
- src/redux/modules/AuctionSlice.js
[Modify] 채팅 데이터 비우기, 마이페이지 등급 수정
> [Modify] 채팅 데이터 비우기, 마이페이지 등급 수정

- src/redux/modules/MemberSlice.js
> [Modify] 카카오 로그인 기능 수정

- src/components/auctionBody/AuctionColumn.jsx
- src/components/auctionBody/AuctionRow.jsx
- src/pages/auctionDetail/AuctionDetail.jsx
- src/pages/auctionReview/AuctionReview.jsx
- src/pages/event/Event.jsx
- src/pages/main/Main.jsx
- src/pages/search/Search.jsx
- src/pages/userProfile/UserProfile.jsx
[Modify] 상세화면 이전 데이터 로드 삭제, 이벤트 모달 삭제
> [Modify] 상세화면 이전 데이터 로드 삭제, 이벤트 모달 삭제

- src/components/auctionBody/AuctionColumn.jsx
- src/components/hooks/UseCountDown.jsx
- src/pages/auctionDetail/AuctionDetail.jsx
- src/pages/chat/Chat.jsx
- src/pages/main/Main.jsx
- src/redux/modules/AuctionSlice.js
> [Modify] 경매 시간 마이너스 해결

- src/components/swipeImage/SwipeImage.jsx
- src/components/swipeImage/SwipeImage.styled.js
- src/pages/auctionDetail/AuctionDetail.jsx
- src/pages/myGrade/MyGrade.jsx
- src/pages/myGrade/MyGrade.styled.js
- src/pages/userProfile/UserProfile.jsx
- src/shared/images/icon/NextImg.svg
- src/shared/images/index.js
[Feat] 메인화면 이미지 슬라이드 버튼 추가
[Modify] 다른 유저 프로필 닉네임 수정
> [Feat] 메인화면 이미지 슬라이드 버튼 추가, [Modify] 다른 유저 프로필 닉네임 수정

- src/components/swipeImage/Slider.jsx
- src/pages/auctionList/AuctionList.jsx
디테일 들어가고 다시 리스트로 뒤로 가기 하면 페이지 네이션 안되는것 수정
> [feat] 옥션 리스트 페이지 네이션 오류 수정

- src/components/header/Header.jsx
- src/components/swipeImage/SwipeImage.jsx
- src/pages/myPage/MyGrade.jsx
- src/pages/myPage/MyPage.styled.js
> [Modify] 등급 이미지 수정, 등급 내용 수정
